import { VOICE_TIERS, VOICE_RIGHTS_PRICING } from '@/lib/config/pricing.config';

const voiceById = Object.fromEntries(VOICE_TIERS.map(t => [t.id, t]));

export const PRICING_TIERS = [
  {
    id: 'tier-1',
    title: voiceById['tier-1'].name,
    tagline: "Speed Meets Quality",
    subtitle: voiceById['tier-1'].description,
    price: `US$${voiceById['tier-1'].price}`,
    unit: "/ block (approx. 1 min)",
    subtext: null,
    buttonText: "Start Project",
    gradient: 'from-green-600 to-teal-600',
    features: [
      "Pure AI generation",
      "Standard Commercial Rights included",
      "2 rounds of AI retakes & regenerations",
      "Minor script updates allowed",
      "24-hour fast delivery",
      "WAV + MP3 high-quality delivery",
      "Self-serve client portal access",
    ],
    deliverables: [
      { name: 'WAV + MP3 high-quality delivery', included: true },
      { name: 'Self-serve client portal access', included: true },
      { name: 'Custom delivery formats & stems', included: false },
      { name: 'Dedicated production manager', included: false },
      { name: 'Multi-language project coordination', included: false },
    ],
    rights: [
      { name: 'Standard Commercial (YouTube / Social)', included: true },
      { name: `Broadcast TV & Full Media Buyout (+US$${VOICE_RIGHTS_PRICING['tier-1'].broadcast})`, included: false },
      { name: `Global TV & Game Rights (+US$${VOICE_RIGHTS_PRICING['tier-1'].global})`, included: false },
    ],
    quickStats: [
      { icon: 'clock', text: '24-Hour Delivery' },
      { icon: 'repeat', text: '2 AI Retakes' },
      { icon: 'audio', text: '~1 Min Block' },
      { icon: 'users', text: 'Pure AI Generation' },
    ],
    numericPrice: voiceById['tier-1'].price,
    highlighted: false,
    isCustom: false,
    badge: null,
    badgeStyle: null,
  },
  {
    id: 'tier-2',
    title: voiceById['tier-2'].name,
    tagline: "Studio Polish, AI Speed",
    badge: "MOST POPULAR",
    subtitle: voiceById['tier-2'].description,
    price: `US$${voiceById['tier-2'].price}`,
    unit: "/ block (approx. 1 min)",
    subtext: null,
    buttonText: "Start Project",
    gradient: 'from-blue-600 to-cyan-600',
    features: [
      "AI + Human Director emotional tuning",
      "Standard Commercial Rights included",
      "2 rounds of Director revisions",
      "Original actor micro-patching included (if needed)",
      "100% perfect pronunciation guarantee",
      "Priority delivery queue",
      "WAV + MP3 high-quality delivery",
    ],
    deliverables: [
      { name: 'WAV + MP3 high-quality delivery', included: true },
      { name: 'Priority delivery queue', included: true },
      { name: 'Original actor micro-patching', included: true },
      { name: 'Custom delivery formats & stems', included: false },
      { name: 'Dedicated production manager', included: false },
    ],
    rights: [
      { name: 'Standard Commercial (YouTube / Social)', included: true },
      { name: `Broadcast TV & Full Media Buyout (+US$${VOICE_RIGHTS_PRICING['tier-2'].broadcast})`, included: false },
      { name: `Global TV & Game Rights (+US$${VOICE_RIGHTS_PRICING['tier-2'].global})`, included: false },
    ],
    quickStats: [
      { icon: 'clock', text: 'Priority Delivery' },
      { icon: 'repeat', text: '2 Director Revisions' },
      { icon: 'audio', text: '~1 Min Block' },
      { icon: 'users', text: 'AI + Human Director' },
    ],
    numericPrice: voiceById['tier-2'].price,
    highlighted: true,
    isCustom: false,
    badgeStyle: 'gold',
  },
  {
    id: 'tier-3',
    title: voiceById['tier-3'].name,
    tagline: "Premium Custom Sessions",
    badge: "PREMIUM",
    subtitle: voiceById['tier-3'].description,
    price: `From US$${voiceById['tier-3'].price}`,
    unit: "",
    subtext: null,
    buttonText: "Consult a Producer",
    gradient: 'from-amber-600 to-orange-600',
    features: [
      "100% Human actor studio recording",
      "Broadcast & Full Media Buyout options available",
      "1 round of performance pickups (script changes billed separately)",
      "Live directed session available",
      "Dedicated production manager",
      "Custom delivery formats & stems",
      "Multi-language project coordination",
    ],
    deliverables: [
      { name: 'WAV + MP3 high-quality delivery', included: true },
      { name: 'Custom delivery formats & stems', included: true },
      { name: 'Dedicated production manager', included: true },
      { name: 'Live directed session', included: true },
      { name: 'Multi-language project coordination', included: true },
      { name: '1 round of performance pickups', included: true },
    ],
    rights: [
      { name: 'Standard Commercial (YouTube / Social)', included: true },
      { name: 'Broadcast TV & Full Media Buyout', included: true },
      { name: 'Global TV & Game Rights', included: true },
    ],
    quickStats: [
      { icon: 'clock', text: 'Custom Timeline' },
      { icon: 'repeat', text: '1 Pickup Round' },
      { icon: 'audio', text: 'Any Duration' },
      { icon: 'users', text: '100% Human Actor' },
    ],
    numericPrice: voiceById['tier-3'].price,
    highlighted: false,
    isCustom: true,
    badgeStyle: 'premium',
  },
];
